parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
extends:
  - airbnb
  - react-app
rules:
  function-paren-newline: 'off'
  global-require: 'off'
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  max-len:
    - error
    - code: 120
      ignoreComments: true
  object-curly-newline: 'off'
  react/no-typos: 'off'
  react/jsx-filename-extension:
    - error
    - extensions:
      - ".js"
  react/jsx-sort-props: 'error'
  semi:
    - error
    - never
env:
  browser: true
  es6: true
  jasmine: true
globals:
  jest: false
  "$Keys": false
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - src
